[theme]
base = "light"
primaryColor = "#13315C"
backgroundColor = "#F6F7F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0B0B0C"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
